// <auto-generated />
namespace App.DbAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class refactor2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(refactor2));
        
        string IMigrationMetadata.Id
        {
            get { return "201611051310091_refactor2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
