// <auto-generated />
namespace App.DbAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class createEmailtable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createEmailtable));
        
        string IMigrationMetadata.Id
        {
            get { return "201611071322252_createEmailtable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
